### ISSUE TITLE
Possible Errors in lexconvert.py for unicode-ipa

### ISSUE THREAD

**Issue by sonofeft** [Rillke/lexconvert#1]
Starting at line 1370 there are several cases of unicode strings that appear to be mis-typed.

('a\u02d0',var5_a_as_in_ah),
    (u'a\u028a',o_as_in_now),
    (u'a\u026a',eye), (u'\u028c\u026a',eye,False),

**Comment by Rillke** [comment]
I pulled updates from http://people.ds.cam.ac.uk/ssb22/gradint/lexconvert.html (f10dc8c94a) - Do you still see these issues?

**Comment by sonofeft** [comment]
Yes, I still see the issues, 
but in the light of day, 
I think only the first string I sent is wrong.

It simply needs a "u" in front of it to make it unicode.

**Comment by ssb22** [comment]
Well spotted. Fixed upstream in v0.264.

**Comment by Rillke** [comment]
@ssb22 Thank you! You would like me to transfer this repo to your account? I can't even remember why I created it in the first place.

**Comment by ssb22** [comment]
Hi Rainer, I've finally mirrored lexconvert with full commit history on GitHub, at https://github.com/ssb22/lexconvert maybe you can just fork that one now? sorry it took so long. Silas

**Comment by Rillke** [comment]
Hey Silas, that is awesome and thanks for letting me know. Do you plan updating the repository at GitHub periodically?

I can't just fork your repo and put it here at this location; that would cause re-users headaches. Maybe I could import the commits as a different branch than master but I prefer if they just switch over to your repository so I added a README.md stating that.

**Comment by ssb22** [comment]
Yes, I've now set up a script to make sure to keep the repo in step whenever I make changes on my website, same as it does with SourceForge.  The commit messages could be a bit more informative I know….
